### ISSUE TITLE
Locale should have labels for Region  and Language

### ISSUE THREAD

**Issue by logan-anderson** [tinalabs/react-tinacms-i18n#18]
instead of the language referring to the language code, it should refer to the code and a label.
 Example:
Instead of
```ts
locale  = {
  region: "ca",
  language: "en",
}
```
it should be
```ts
locale = {
  region: {
         code: 'ca',
         label: 'Canada'
    },
   language: {
      code: 'en',
      label: 'English' 
   }
}
```

There should also be a way to fetch this data async

**Comment by logan-anderson** [comment]
:point_up: What do you think of this @chrisdmacrae

**Comment by chrisdmacrae** [comment]
@logan-anderson yup, this is the right format.

**Comment by jbevis** [comment]
https://github.com/tinalabs/react-tinacms-i18n/pull/28 ready for review.
