### ISSUE TITLE
Add default locale to API options

### ISSUE THREAD

**Issue by chrisdmacrae** [tinalabs/react-tinacms-i18n#25]
Set default on the provider or when constructing the API, and it will default to that language on load, UNLESS currentLocale is applied, in which case that is used instead.

**Comment by jbevis** [comment]
Are we not handling this here:  https://github.com/tinalabs/react-tinacms-i18n/blob/979ced3c13cf93fbfd2639c3018aed709788bd12/src/localizationApi/LocalizationAPI.ts#L64 ?

**Comment by chrisdmacrae** [comment]
@jbevis it's not possible to configure the behaviour:

https://github.com/tinalabs/react-tinacms-i18n/blob/979ced3c13cf93fbfd2639c3018aed709788bd12/src/localizationApi/LocalizationAPI.ts#L37
